### PR TITLE
Add tag builder to client

### PR DESCRIPTION
**Pull request by jharrington22**
This PR implements a tag builder to the awsclient currently it would support EC2 and IAM tags

### CODE REVIEW

**Comment by jharrington22** [comment]
@ArielLima please review

**Comment by iamkirkbater** [comment]
Can we add any tests to the functionality that we're adding with this?

**Comment by ArielLima** [comment]
@jharrington22 tests are failing because of bad indentation

**Comment by ArielLima** [comment]
> Can we add any tests to the functionality that we're adding with this?

I would prefer to fix and merge it ASAP since it is holding up #339 + other things @jharrington22 is working on

**Comment by rogbas** [comment]
/lgtm
/approve
We'll need to address unit tests for this in a following PR, since it blocks 2 other PRs, one of those due for Summit next week

**Pull request merged**
