### PR TITLE
Mock AWS client in accountclaim_controller tests

### PR DESCRIPTION
**Pull request by 2uasimojo**
Previously these tests were making real AWS calls (but not failing because the errors weren't percolating up).

This commit just mocks the AWS client so we're no longer making those calls. A future commit ought to make proper use of the mocks to `EXPECT()` calls appropriately, etc.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
> This commit just mocks the AWS client so we're no longer making those calls. A future commit ought to make proper use of the mocks to `EXPECT()` calls appropriately, etc.

We decided to do the `EXPECT()`ing here. And besides, what I did in here won't work until we have #423 in place, so this will also be rebased thereon.

/hold

**Comment by 2uasimojo** [comment]
> We decided to do the `EXPECT()`ing here. And besides, what I did in here won't work until we have #423 in place, so this will also be rebased thereon.

This is done. Still on /hold until #423 merges.

This can still be [reviewed by ignoring the first commit](https://github.com/openshift/aws-account-operator/pull/419/commits/dbdae075c2600b815e3b93a290a2aec41bf343ce).

**Comment by rogbas** [comment]
@rogbas please review

**Comment by 2uasimojo** [comment]
[Dep](https://github.com/openshift/aws-account-operator/pull/423) merged, clean rebase, ready to go.

**Comment by 2uasimojo** [comment]
> [Dep](https://github.com/openshift/aws-account-operator/pull/423) merged, clean rebase, ready to go.

Whoops, I meant to

/hold cancel

**Pull request merged**
