### PR TITLE
OSD-6851: Pull operator image by digest

### PR DESCRIPTION
**Pull request by 2uasimojo**
...rather than by tag.

[OSD-6851](https://issues.redhat.com/browse/OSD-6851)

### CODE REVIEW

**Comment by iamkirkbater** [comment]
This looks sane to me.  Is the hold because of the change freeze or some other reason?

**Comment by 2uasimojo** [comment]
> Is the hold because of the change freeze or some other reason?

Pending Business Decision

**Comment by 2uasimojo** [comment]
This functionality is included in #547

**Pull request closed without merging**
