### PR TITLE
apis: Move to separate module

### PR DESCRIPTION
**Pull request by vkareh**
To allow for better separation of API versus business logic, we move the apis to be its own module within the operator code. This allows external projects to import just the API as necessary without pulling in potentially-conflicting dependencies.

Also remove api dependency on controller-runtime to allow OCM to import the necessary APIs.

Please see https://issues.redhat.com/browse/OSD-6948

### CODE REVIEW

**Comment by iamkirkbater** [comment]
Integration tests all ran fine locally.

**Comment by jharrington22** [comment]
/lgtm

@rogbas @iamkirkbater I'll leave it to you to approve.

**Pull request merged**
