### PR TITLE
Fix CRDs

### PR DESCRIPTION
**Pull request by drpaneas**

### CODE REVIEW

**Review by 2uasimojo — COMMENTED** [review]
Was this just a reformatting exercise? There’s a CI check that won’t let you deviate from what `operator-sdk generate crds` generates.

**Comment by drpaneas** [comment]
> Was this just a reformatting exercise? There’s a CI check that won’t let you deviate from what `operator-sdk generate crds` generates.

Kind of, yes. I am trying to add a new API field and @iamkirkbater told me that I can do that by modifying the file and then run `make generate`. Without modifying any file, just cloning the repo and running `make generate` I get those changes -- which seems they are not valid. Why is this happening?

**Comment by 2uasimojo** [comment]
> > Was this just a reformatting exercise? There’s a CI check that won’t let you deviate from what `operator-sdk generate crds` generates.
> 
> Kind of, yes. I am trying to add a new API field and @iamkirkbater told me that I can do that by modifying the file and then run `make generate`. Without modifying any file, just cloning the repo and running `make generate` I get those changes -- which seems they are not valid. Why is this happening?

Could be minor variations in versions of tools on your system. We have a tool that runs targets in the same environment CI uses. Try:

```
./boilerplate/_lib/container-make op-generate
```

**Comment by drpaneas** [comment]
> > > Was this just a reformatting exercise? There’s a CI check that won’t let you deviate from what `operator-sdk generate crds` generates.
> > 
> > 
> > Kind of, yes. I am trying to add a new API field and @iamkirkbater told me that I can do that by modifying the file and then run `make generate`. Without modifying any file, just cloning the repo and running `make generate` I get those changes -- which seems they are not valid. Why is this happening?
> 
> Could be minor variations in versions of tools on your system. We have a tool that runs targets in the same environment CI uses. Try:
> 
> ```
> ./boilerplate/_lib/container-make op-generate
> ```

I ran this, but I got this error:

```
boilerplate/openshift/golang-osd-operator/operator-sdk-generate.sh
/bin/ls: cannot access pkg/apis: No such file or directory
No APIs! Skipping operator-sdk generate.
```

I believe this is a regression introduced from https://github.com/openshift/aws-account-operator/pull/545/commits/e64ec2abd702692d477f664a39ee0d07dc575653

I've tried to fix it, but operator-sdk binary assumes that path:

```
$OSDK generate crds $_osdk_generate_crds_flags

# Produces this:
FATA[0000] error generating CRDs from APIs in pkg/apis: error generating CRD manifests: error reading CRD cache dir deploy/crds: open deploy/crds: file does not exist 
```

**Comment by rogbas** [comment]
PR testing PR checks, closing it

**Pull request closed without merging**
