### PR TITLE
Add prometheus role and rolebinding to the generated CSV

### PR DESCRIPTION
**Pull request by fahlmant**
This PR adds the needed prometheus-k8s RBAC objects to the generation of the CSV

### CODE REVIEW

**Comment by lisa** [comment]
@jewzaam I'm not 100% sure about the saasherder directory. Maybe @jharrington22 or @jmelis ?

**Comment by jharrington22** [comment]
@jewzaam I put a hold on this because of the role binding I knew it wasn't specified in CSV so I wanted to double check, thanks I'll remove it now.

@lisa @jewzaam we don't want this role bound to the service account?

**Comment by jewzaam** [comment]
> @jewzaam I put a hold on this because of the role binding I knew it wasn't specified in CSV so I wanted to double check, thanks I'll remove it now.
> 
> @lisa @jewzaam we don't want this role bound to the service account?

We want this bound to the `prometheus-k8s` SA in `openshift-monitoring`. See: https://github.com/openshift/aws-account-operator/blob/master/deploy/prometheus-k8s-rolebinding.yaml#L9-L12

You need to drop the role and rolebinding yaml in the bundle.  This is done for crds here:
https://github.com/openshift/aws-account-operator/blob/master/hack/generate-operator-bundle.py#L45-L49

Same can be done for any ClusterRole, ClusterRoleBinding, Role, and RoleBinding.

**Pull request closed without merging**
