### PR TITLE
Prevents possible race condition while trying to access byoc secret

### PR DESCRIPTION
**Pull request by ArielLima**
Card -> https://issues.redhat.com/browse/OSD-6386

### CODE REVIEW

**Comment by iamkirkbater** [comment]
/hold

Holding for anyone else to share their thoughts. Ari and I discussed this implementation before he completed it and we figured this would be the easiest way to head-off any possible race condition without spending much more time than necessary on it.

**Comment by iamkirkbater** [comment]
/lgtm

Local tests passed for me.  Still holding for comment.  Will hold until Wednesday sometime.

**Comment by rogbas** [comment]
This is looking good, and if we merge it today we can get it promoted on time for tomorrow's load test.

/hold cancel

**Pull request merged**
