### PR TITLE
accountclaims: Accept ExternalID when calling AssumeRole

### PR DESCRIPTION
**Pull request by vkareh**

### CODE REVIEW

**Comment by iamkirkbater** [comment]
For context - This is to support the ExternalID for the AssumeRole command, which Customer X has requested as necessary for all AssumeRoles into their cluster: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html

**Review by jharrington22 — COMMENTED** [review]
This looks good though you'll need to run `operator-sdk generate k8s/crds`

**Comment by iamkirkbater** [comment]
Try running (from the AAO root directory) `./boilerplate/_lib/container-make generate`

**Comment by vkareh** [comment]
@iamkirkbater @jharrington22 - does this look good now?

**Comment by jharrington22** [comment]
@vkareh looks good to me!

**Comment by jharrington22** [comment]
@iamkirkbater @lisa this should be able to merge anytime.

**Comment by iamkirkbater** [comment]
/lgtm

Tested locally.

**Pull request merged**
