### PR TITLE
Update OWNERS file - approvers and reviewers lists

### PR DESCRIPTION
**Pull request by rogbas**
Adding @lisa and @drpaneas as reviewers, and @iamkirkbater as approver.

### CODE REVIEW

**Comment by iamkirkbater** [comment]
Before we merge this do we need to put `hold`s on the open PRs I have so they don't all auto-merge after this is merged if someone else `LGTM`'d them?

**Comment by rogbas** [comment]
@iamkirkbater I don't think so, but it's good to be safe, I've put on hold all PRs owned/LGTMed by you.

**Comment by iamkirkbater** [comment]
Excellent.

/lgtm

**Comment by lisa** [comment]
hey wait a minute, this was merged while i was on holiday! 😆  😆 🇨🇦

**Pull request merged**
