### PR TITLE
Paginate through accounts, return err if none found

### PR DESCRIPTION
**Pull request by jharrington22**
The PR ensure we paginate through all AWS accounts and finally that we check to see that we actually found and account or else return an error.

### CODE REVIEW

**Comment by jharrington22** [comment]
@rafael-azevedo @fahlmant could you both please re review? This should be quicker though doesn't address the duplicate account issue at the moment.

**Comment by rafael-azevedo** [comment]
LGTM

**Comment by jharrington22** [comment]
@fahlmant @rafael-azevedo sorry another review, obviously slower since we're going to still paginate all accounts it will now return an error if there is duplicate account names.

**Comment by rafael-azevedo** [comment]
LGTM , should the commits be squashed ?

**Comment by jharrington22** [comment]
@rafael-azevedo I'll squash and merge

**Pull request merged**
