### PR TITLE
Boilerplate update removing `operator-sdk generate`

### PR DESCRIPTION
**Pull request by 2uasimojo**
This PR comprises three commits:
- Automated boilerplate update. Importantly, this brings in
  - Ability to securely suppress boilerplate deltas in GitHub via `.gitattributes`. (Suppression is _not_ included in this PR.)
  - The operator image is now built against golang 1.16 (was: 1.13).
  - The OLM catalog images are now built against registry 4.8.0 (was: 4.7.0). This upgrade includes some security fixes.
- Cleanup and code regeneration pursuant to the above.
- Another boilerplate update. Should have zero effect. Just brings in some commits that happened while this PR was waiting for review.

See individual commit messages for details.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Depends-On: https://github.com/openshift/release/pull/18898

**Comment by 2uasimojo** [comment]
Trivial rebase

**Comment by 2uasimojo** [comment]
This will now need to be reconciled with #580. I *think* we should just be able to revert the [last four commits](https://github.com/openshift/aws-account-operator/compare/243201a4d2be5dcb14cb00e020c596ff36113a61...5a36c9eb9cfd877049da90b3c228cac3035bb96c?expand=1).

**Comment by dastergon** [comment]
@2uasimojo how can we proceed here?

**Comment by 2uasimojo** [comment]
I'm [working with @sam-nguyen7](https://coreos.slack.com/archives/CMD1L32M9/p1627564620381200).

I've finished rebasing and cleaning up #589, which supersedes this, so we can close.

**Pull request closed without merging**
