### PR TITLE
Added a help target in Makefile

### PR DESCRIPTION
**Pull request by dastergon**
The Makefile is already more than 300 LoC and that makes it difficult to check for the various available targets. Consequently, I created a help target to display a list of all the available targets. I used most of the current comments in the Makefile. The comments could be improved, but this can happen in another iteration.

Example output:
```shell
$ make help

Usage:
  make <target>
  help             Display this help
  check-aws-account-id-env  Check if AWS Account Env vars are set
  check-ou-mapping-configmap-env  Check if OU mapping ConfigMap Env vars are set
  create-account   Create account
  delete-account   Delete account
  test-account-creation  Test Account creation
  create-accountclaim-namespace  Create account claim namespace
  delete-accountclaim-namespace  Delete account claim namespace
  create-accountclaim  Create AccountClaim
  delete-accountclaim  Delete AccountClaim
  create-awsfederatedrole  Create awsFederatedRole "Read Only"
  delete-awsfederatedrole  Delete awsFederatedRole "Read Only"
  create-awsfederatedaccountaccess  Create awsFederatedAccountAccess - This uses a AWS Account ID from your environment
  delete-awsfederatedaccountaccess  Delete awsFederatedAccountAccess - This uses a AWS Account ID from your environment
  test-awsfederatedrole  Test Federated Access Roles
  test-switch-role  Test switch role
  test-awsfederatedaccountaccess  Test awsFederatedAccountAccess
  create-ccs-namespace  Create CCS (BYOC) namespace
  create-ccs-2-namespace  Create CCS (BYOC) namespace
  delete-ccs-namespace  Delete CCS (BYOC) namespace
  delete-ccs-2-namespace  Delete CCS (BYOC) namespace
  create-ccs-secret  Create CCS (BYOC) Secret
  create-ccs-2-secret  Create CCS (BYOC) Secret
  delete-ccs-2-secret  Delete CCS (BYOC) Secret
  create-ccs-accountclaim  Create CSS AccountClaim
  create-ccs-2-accountclaim  Create CSS AccountClaim
  delete-ccs-accountclaim  Delete CCS AccountClaim
  delete-ccs-2-accountclaim  Delete CSS AccountClaim
  test-ccs         Test CCS
  create-ccs       Deploy a test CCS account
  delete-ccs       Teardown the test CCS account
  create-s3-bucket  Create S3 bucket
  list-s3-bucket   List S3 bucket
  test-reuse       Test reuse
  test-secrets     Test secrets are what we expect them to be
  deploy-aws-account-operator-credentials  Deploy the operator secrets, CRDs and namesapce.
  predeploy-aws-account-operator  Predeploy AWS Account Operator
  predeploy        Predeploy Operator
  deploy-local     Deploy Operator locally
  deploy-cluster   Deploy to cluster
  check-aws-credentials  Check AWS Credentials
  create-ou-map    Test apply OU map CR
  delete-ou-map    Test delete OU map CR
  test-aws-ou-logic  Test AWS OU logic
  test-all         Test all
  clean-operator   Clean Operator
  go-check         Golang linting and other static analysis
  go-build         Build binary
```
PTAL

### CODE REVIEW

**Review by drpaneas — APPROVED** [review]

**Comment by iamkirkbater** [comment]
codecov bot what are you even looking at?!?! haha

This looks great, however I'm going to hold this due to the change freeze.

/hold

/lgtm

**Pull request merged**
