### PR TITLE
Improve failure path messages

### PR DESCRIPTION
**Pull request by dastergon**
Added messages in errors that weren't returning a meaningful message.

PTAL

### CODE REVIEW

**Comment by drpaneas** [comment]
Thanks :)

Since you are going down the rabbithole of errors, could you possibly add/revisit some relative text error messages for better logging on the various instances found at the same file (that is `cmd/manager/main.go`)? e.g. `log.Error(err, "Coffee not found")`

**Comment by iamkirkbater** [comment]
Agreeing with Panos here.  Can you just take a quick look at the other errors in this file, and then squash the commits down to a single one?  LGTM so far :)  Thanks!

**Comment by dastergon** [comment]
@iamkirkbater unfortunately, I can't invest time to work on this PR right now due to the Cluster Relocation epic, but I will get back to it soon.

**Comment by dastergon** [comment]
@iamkirkbater I've updated my changes. PTAL

**Comment by iamkirkbater** [comment]
Nice work! 

/lgtm

**Pull request merged**
