### PR TITLE
sets controller reference for secrets created

### PR DESCRIPTION
**Pull request by dofinn**
This will delete an accounts corresponding secret upon account deletion.

### CODE REVIEW

**Comment by jharrington22** [comment]
@dofinn looking good I will take a look and test this tomorrow.

**Comment by fahlmant** [comment]
@dofinn Trying to test this, could you fix the conflicts?

**Comment by jharrington22** [comment]
@dofinn Did you mean to close this PR?

**Comment by fahlmant** [comment]
@jharrington22 This code got merged in #276

**Pull request closed without merging**
