### PR TITLE
Moves complex logic and simple checks to function that return boolean results

### PR DESCRIPTION
**Pull request by clcollins**
This change moves some simple checks and complex logic to functions that
    return boolean results for the different possible states of the account,
    allowing more testable checks readable code.
    
    Also includes tests for the new functions to validate they are returning
    the correct output given the expected account input.
    
    Signed-off-by: Christopher Collins <collins.christopher@gmail.com>

### CODE REVIEW

**Comment by ArielLima** [comment]
/lgtm

**Tests performed:**

- Created a normal account
- Created a BYOC account
- FederatedAccess make test

Had no issues

**Comment by rogbas** [comment]
@clcollins Could you please rebase with the latest Makefile target changes for automated testing so people can run their own checks? Note: wait for the PR with `make test-all` option to be merged.

**Comment by clcollins** [comment]
Rebased with the latest `make test-all` changes, and ran through that on this PR with no visible issues.  I think it's good, but given the size, I'd appreciate some eyes on the different logic bits being consolidated into functions.

CC @rogbas

**Pull request merged**
