### PR TITLE
Implement conditions status for the Account CRDs

### PR DESCRIPTION
**Pull request by fahlmant**
Adds AccountCondition defintions to the AccountStatus

### CODE REVIEW

**Comment by jharrington22** [comment]
@fahlmant you need to run `operator-sdk generate k8s`

**Comment by fahlmant** [comment]
@jharrington22 done

**Comment by jharrington22** [comment]
@fahlmant Sorry can you pull master of the operator-sdk `make dep && make install` then run 

```
operator-sdk generate k8s
operator-sdk generate openapi
```

**Comment by fahlmant** [comment]
@jharrington22 Done

**Comment by jharrington22** [comment]
LGTM

**Pull request merged**
